### ISSUE TITLE
Does MuZeroNetwork work; batch size

### ISSUE THREAD

**Issue by CheckerBored** [JimOhman/model-based-rl#3]
Thanks for this RL implementation.

Is the option `--environment MuZeroNetwork` currently working? I'm new to PyTorch, but if I'm reading the code correctly it seems that the MuZeroNetwork is hardcoded to expect batches of 64, but the trainer appears to only ever send single observations:

```
current_observation = np.float32(game.get_observation(-1))
if self.config.norm_states:
 current_observation = (current_observation - self.obs_min) / self.obs_range
current_observation = torch.from_numpy(current_observation).to(self.device)
```

This always results in an error like this (this example from a test run with the LunarLander game, which returns an (1, 8)-dimensional observation, but it happens with any game):

```
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 1, 3, 3], but got 2-dimensional input of size [1, 8] instead
```

Perhaps this also explains why I'm getting worse performance on GPU than on CPU when using the FCNetwork, regardless of the batch size I set?

**Comment by JimOhman** [comment]
Thank you for using it.

I assume you meant to write --architecture MuZeroNetwork, then yes, it should work. However, the MuZeroNetwork contains 2d-convolutions, which means that the states needs to be two dimensional, ex. images. Games with one dimensional states, that has pre-selected features, i.e. the LunarLander game, the FCNetwork or similar feed-forward architectures are the way to go.

Regarding the batch size, it is not actually hard-coded. In PyTorch it is sort of hidden, as the amount of samples you put in is what you get out, so in theory you can change the batch size at any time during training if you want to. The actors only use one sample in each forward-pass to the network, but the learner use --batch_size 256 number of samples instead. The 64 you see in the first weight of MuZeroRepresentation is the amount of output channels from the first convolution layer, which is sort of arbitrary.

Regarding the GPU vs. CPU speed, it depends on the size of the network as well, if the network is "small" the overhead from using the GPU will make it slower than using CPU. However, there should be a large enough batch size for any sized network that makes GPU faster than CPU, but the agents performance might not be better simply because the batch size is larger.

**Comment by ipsec** [comment]
Hi,

Are you talking about --architecture?
I might be wrong, but the MuZeroNetwok was designed to work with Atari games when the observation are images/frames. 
So it use convolutional layers.

LunarLander use a full connected network.

**Comment by CheckerBored** [comment]
Thanks both for your very helpful feedback. Yes, I was referring to ``--architecture MuZeroNetwork``, and yes, it seems I misunderstood how PyTorch batching works.

I'm not sure what's going on with the batch size/GPU performance issue, since even setting something silly like ``--batch_size 16384`` isn't improving my performance relative to CPU, but I'll keep working on it. It may have something to do with the fact that my GPU is on a Windows machine, and Ray only supports Windows experimentally.

Thanks again.
